-- Deprecated migration (NO-OP)
--
-- The real implementation is in:
--   supabase/migrations/migration_instagram_stats_refresh_rpc.sql
--
-- This file previously created a stub function that made the UI show
-- "Статистика обновлена", while not inserting rows into instagram_stats.
-- It is intentionally left empty now to avoid overwriting the real function.
